### ISSUE TITLE
Price and features

### ISSUE THREAD

**Issue by StephenHaney** [steveruizok/telestrator#5]
You've captured my interest with this project. Hopefully this is a good place to put these kind of thoughts.

I would definitely purchase this app if it was in the App Store. I think my happy price would be ~$3-5 with the current feature set. Similar to a "Magnet" type app.

A feature that would increase my price interest (10x) would be the ability to add annotations over top of previously recorded screen captures (without reducing the capture quality on the output). This could even work by recording only my drawings over transparent space and requiring me to layer that recording over my content inside separate editing software.

I know this is prototype phase, but I'll open a few issues with what's blocking me from using it for real already — all with the intention of being helpful information. Please take only what's useful.

**Comment by steveruizok** [comment]
Appreciate the issues! There are a few things I'd like to add before releasing, but I'm already looking at my options for distribution. Speaking of those extra features...

> A feature that would increase my price interest (10x) would be the ability to add annotations over top of previously recorded screen captures (without reducing the capture quality on the output). This could even work by recording only my drawings over transparent space and requiring me to layer that recording over my content inside separate editing software.

I have the same need, and I've been thinking about solutions.

The most obvious would be to offer an option to set the window's background color to chroma key green, so that we could use a chroma key filter to composite a recording onto the actual video. I've tried this approach early on with OBS and it worked fine. A related option would be to make the tool itself use a chroma key color for marks, so that you could still draw over the video playback and composite using a _reverse_ chroma key filter.

A more complex solution would to capture timestamps for each event and allow a user to play back a session. Again, the approach would be to draw directly on top of previously recorded video (using a transparent background), then repeat the session against an opaque key color background while recording, and finally compositing using a chroma key filter.

I'll start with just that option to use a chroma key background color / color, and we'll see if the more complex part is needed.

**Comment by StephenHaney** [comment]
Makes sense. For my use case I'd need to see the content as I'm drawing, so the first solution probably wouldn't work (if I'm understanding correctly that you'd see a chroma key background as you draw over it).

The second one would work, albeit with some manual labor involved.

I suppose the ultimate would be if I could draw over top of my screen (I'd play the recording full screen underneath) and the app itself could export a video file of my drawing over top of a chroma key background. Of course, that may be significantly more scope and more tech than you're looking to push into the electron app.

**Comment by steveruizok** [comment]
There may be a way to trick the screen recording software into "seeing" a chroma key background instead of the transparent background that you would see. Worth looking into. But apart from that, I think the reverse chroma key approach may be the most straightforward.
