### ISSUE TITLE
external monitor support?

### ISSUE THREAD

**Issue by argyleink** [steveruizok/telestrator#7]
I havent been able to draw on my 2nd monitor on macOS, works great on the primary 👍🏻

**Comment by steveruizok** [comment]
Hey, I'm still exploring options for this. In the short term, you can use Mission Control to move the Telestrator window to another screen. Something I'd like to add is the ability to move the control panel to the right side, rather than the left; because if your second monitor is arranged to the right of your primary monitor, it's very difficult to open the panel by hovering over it.

![image](https://user-images.githubusercontent.com/23072548/110176268-ef004380-7dfa-11eb-82fd-5cd06469e02b.png)

**Comment by argyleink** [comment]
oh nice, that's a good way to do that, i've been clicking on it on the dock and picking which desktop it's on 👍🏻  going to close this since it can be used on a 2nd monitor, but i think what i really need is "any monitor", but that's a different feature request 🙂
